apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://charts.fairwinds.com/stable
      chart: vpa
      targetRevision: 5.1.0
      helm:
        valueFiles:
          - $values/addons/vertical-pod-autoscaler/values.yaml
    - repoURL: git@github.com:kkato/k8s
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
