repositories:
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts

releases:
  - name: tempo
    namespace: monitoring
    createNamespace: true
    chart: grafana-community/tempo
    version: 3.0.0
    values:
      - values.yaml
